### ISSUE TITLE
NTAG213

### ISSUE THREAD

**Issue by bidyutper** [trteodor/RFID-RC522-STM32F1-ExampleTest#1]
Hi how to Read UID of NTAG 213..Reading only 4 byte My NTAG 213 have 7byte.

**Comment by trteodor** [comment]
I rly dk,
But if u read 4 bytes so what is problem to read is sequentially? : / It isn't possible?
Just read 4bytes save it, and read next 4 and read next 4...? :/

**Comment by bidyutper** [comment]
This one is Mifare card which is reading ok.
![Screenshot_20210814-170025_TagInfo](https://user-images.githubusercontent.com/16462057/129445000-dccfb39e-adc5-49ae-af00-3d0d014c82c6.jpg)

But I want to read NTAG Tag ID only

![Screenshot_20210814-165938_TagInfo](https://user-images.githubusercontent.com/16462057/129445064-ade8fa6a-187d-4bce-91cf-06031bea6071.jpg)

**Comment by bidyutper** [comment]
Note; NTAG 7byte UID

**Comment by trteodor** [comment]
Man, i'am sorry i rly dk. I'am not specialist :( You Should ask on forums or somewhere, anyway goodluck in solving your challenge/ problem :)
